apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: kube-runner
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: karthickme/ke_devops