redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 2

applicationSet:
  replicas: 2

global:
  domain: argocd.ke.com

certificate:
  enabled: true

server:
  replicas: 2
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    enabled: true
    ingressClassName: nginx
    tls: true